DROP TABLE t_user;/*SQL@Run*//*SkipError*/
CREATE TABLE t_user(
    USER_ID INT NOT NULL AUTO_INCREMENT  COMMENT '用户ID' ,
    USER_NAME VARCHAR(32) NOT NULL   COMMENT '用户名' ,
    USER_ALIAS VARCHAR(32)    COMMENT '昵称' ,
    USER_PWD VARCHAR(32) NOT NULL   COMMENT '密码' ,
    USER_EMAIL VARCHAR(32)    COMMENT '邮箱' ,
    USER_CREATE_TIME INT NOT NULL   COMMENT '注册时间 时间戳' ,
    USER_STATUS INT NOT NULL  DEFAULT 1 COMMENT '状态 1：生效；
0：停用' ,
    USER_IMG VARCHAR(32)    COMMENT '头像' ,
    PRIMARY KEY (USER_ID)
) COMMENT = '用户表';/*SQL@Run*/
ALTER TABLE t_user COMMENT '用户表';/*SQL@Run*/
